# molecule/default/molecule.yml
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2004-ansible
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      ansible_cfg: ../../playbook/ansible.cfg  # Ajusta la ruta según sea necesario
  playbooks:
    converge: ../../playbook/playbook.yml
verifier:
  name: ansible
  playbook: molecule/ckan/verify.yml